kubernetes/launch-job.sh

Changes to `kubernetes/launch-job.sh`:
* Can resume jobs by adding `-r <timestamp>` flag
* Also, unrelated: fix flag parsing so that `./launch-job -h` prints the usage message as desired

`kubernetes/launch-job.sh`: Allow resuming jobs

---

kubernetes/launch-job.sh

Changes:
* If `EXTRA_VICTIMPLAY_GPUS` is 0, then we should only launch the `-essentials` job and not the `-victimplay` job, as the `-victimplay` job has 0 replicas.
* `ctl job run` does error when there are 0 replicas, but before it errors, it creates a persistentvolume that it does not clean up

`kubernetes/launch-job.sh`: Don't launch extra job if `EXTRA_VICTIMPLAY_GPUS == 0`

---

kubernetes/launch-common.sh
kubernetes/launch-job.sh
kubernetes/launch-match.sh
kubernetes/update_images.py

As part of code de-duplication we ended up always building just C++ image. I've refactored the update_images call to be a function and take arguments for what images to build.
I also noticed Python script isn't executable and missing shebang. Seems generally better for script to declare what interpreter it needs rather than relying on callees, so quickly changed it.

Hotfix: build Python image in launch-jobs.sh

---

compose/cpp/Dockerfile
compose/python/Dockerfile
kubernetes/curriculum.sh
kubernetes/log-git-commit.sh
kubernetes/match.sh
kubernetes/shuffle-and-export.sh
kubernetes/update_images.py

Logs the git commit for an experiment in a `commit` file:
* `kubernetes/update_images.py` passes in the git commit as a `--build-arg`, which is saved as environment variable `GIT_COMMIT` inside the image
* `kubernetes/log-git-commit.sh` logs a timestamp and commit into a file called `commit` in the experiment output directory
(optional reading)
We also discussed logging the Docker digest/hash, which I did not implement in this PR. A few reasons:
* ideally the git commit is enough to look up the image in Docker Hub or to rebuild the image
* docker digests are kinda confusing — there's the digest you see on Docker Hub, then there's the platform-specific digest you get [when you pull from Docker Hub](https://github.com/docker/hub-feedback/issues/1925), and then there's the image ID, all of …

kubernetes: Log git commit for experiments

---

kubernetes/launch-job.sh

Context: `ctl` only allows jobs with up to ~50 characters, otherwise we hit Kubernetes' [63-character name limit](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) after appending `-launch-0-0` or a random volume-mount suffix. I've hit the character limit several times due to having verbose names.
Changes: This PR changes `kubernetes/launch-job.sh` to make the job name be `go-train-$PREFIX-{vital,extra}` instead of `go-training-$PREFIX-{essentials,victimplay}`, saving a few extra characters that can be used for $PREFIX.

kubernetes: Shorten job name

---

kubernetes/launch-match.sh
kubernetes/match.sh

Changes to `kubernetes/launch-match.sh`
* Remove `VICTIM` and `ADVERSARY` positional arguments
* We don't always want to launch a match between two bots. I recently launched an experiment where I had a config file with ~10 bots and I didn't want to have to specify `VICTIM` and `ADVERSARY. 
* If the user of `launch-match` wants to override the models specified in the config file, they can do `./launch-match <jobname> -- -override-config nnModelFile0=...` instead
* Make the launched job have `--high-priority`
* we want these jobs to have priority over the low-priority extra victimplay workers launched by `kubernetes/launch-job.sh`

launch-match: Remove required victim/adversary arguments

---

compose/transfer/compose.yml
compose/transfer/launch.sh
configs/raw-gtp.cfg

Unfortunately due to the apparent discrepancies between `analysis` and (our version of) `match`, it's become necessary to check that our attacks "transfer" to `KataGo-raw`.
The `raw-gtp.cfg` file is necessary because `KataGo-raw` doesn't support config options with player indices in GTP mode. Also it forces you to specify explicitly that `ponderingEnabled=false`.

Support transfer experiments with KataGo-raw

---

scripts/baseline_attack.py

Nora renamed `playouts` to `visits` in `baseline_attack` at some point, but I think there was an undetected merge conflict where I did not rename an instance of `playouts`.

baseline_attack: `num_playouts` -> `num_visits`

---

compose/transfer/compose.yml
compose/transfer/launch.sh
scripts/baseline_attack.py
src/go_attack/baseline_attack.py

For consistency we probably want to run our baseline attacks against KataGo with komi set to 6.5 rather than the default of 7.5. This PR makes komi configurable in `scripts/baseline_attack.py` via a flag.
* launched baseline attack against KataGo and checked that custom komi is saved in the SGFs
* launched baseline attack against Leela with a komi of 999 and checks that at the end of the game, Leela outputs that White wins by a huge margin

baseline_attack: Allow Komi to be specified

---

scripts/score_with_katago.py

KataGo scoring clears out opposite-color stones within pass-alive groups. For consistency throughout experiments, we should use KataGo scoring everywhere (including in experiments where otherwise KataGo isn't involved at all like baseline attacks vs. ELF).
Adds script that rescores SGFs using KataGo.
* Run `python scripts/score_with_katago.py /nas/ucb/ttseng/go_attack/match/adv-checkpoints/0-redo/sgfs/`
* Here we expect no change in scores since these are KataGo `match` games
* Run  `python scripts/score_with_katago.py /nas/ucb/ttseng/go_attack/transfer/`
* Here we expect changes in score since these are scored without analyzing pass-alive groups
* Mean squared error from score changes: 274.4 (no games changed winners though)

scripts: Add script to rescore SGFs using KataGo

---

configs/curriculum.json

Changes:
* Increase win rate threshold from 0.5 to 0.75
* Tony suggested this change a while ago so that we can't get an adversary that only wins as one color. It also means we spend marginally more time training on weaker adversaries than require less compute to evaluate.
* Change last checkpoint to be cp505-v1048576 instead of just cp505-v1600

Curriculum: Update win rate threshold and max visits

---

src/go_attack/baseline_attack.py

When running multiple KataGo configs in parallel in `scripts/baseline_attack.py`, we should quit KataGo at the end of each run. Otherwise the KataGo process is leaked and takes up GPU memory until all runs are finished and `scripts/baseline_attack.py` terminates.

baseline_attack: Quit KataGo after finishing

---

configs/emcts1/components/board-sizes.cfg

Bug: `board-sizes.cfg` lists board sizes first grouped by odd board lengths and by even board length, whereas `komi-handicap.cfg`'s `komiByBSize` does not list komis grouped by odd/even lengths. The result is that we're accidentally setting komi=9.5 instead of 6.5 for 9x9 boards and komi=6.5 instead 9.5 for 8x8 boards.
Fix: reorder board sizes in `board-sizes.cfg`.

configs: Fix komis being swapped for small board sizes

---

src/go_attack/baseline_attack.py

* In SGFs generated by `baseline_attack.py`, label `PB[]` and `PW[]` with the adversarial policy and victim for easier parsing.
Example output SGF (edge attack vs. /dev/null):
```
(;FF[4]SZ[7]RU[NZ]KM[6.5]PB[victim]PW[adv-baseline-edge]C[Edge attack; Black victim]RE[W+6.5]
;B[fe];W[ag];B[be];W[bg];B[fb];W[gb];B[gg];W[gf];B[ea];W[aa];B[df];W[ca];B[ff];W[gc];B[ec];W[ae];B[cc];W[dg];B[];W[])
```

baseline_attack: Label PB[] and PW[] with adversary and victim

---

compose/transfer/launch.sh

Fixes to launch script for transfer experiments:
* Parse flags until we see a non-flag, not until the last two arguments (otherwise we won't correctly print a usage message if we run with the arguments `-h foobar`)
* Clean up Docker networks even if the job is interrupted
* Build images before launching (otherwise every launched game may in parallel attempt to build the same Docker images simultaneously)
* `shellcheck` linting

compose/transfer/launch.sh: Fix small usability issues

---

configs/match.cfg

Changes:
* Make `match.cfg` config closer to `gtp-base.cfg` config by making match's temperature parameters match GTP's. (`gtp-base.cfg` does not specify the temperature parameters, which gives the default values `chosenMoveTemperature = 0.20, chosenMoveTemperatureEarly = 0.60`.)
Discussion on why we should make the match config closer to the GTP config: https://farinc.slack.com/archives/C01R2R7NH2P/p1672118741210689
For reference, gtp-base.cfg is
```
allowResignation = false
cudaUseNHWC = true
deviceToUseThread0 = 0
deviceToUseThread1 = 0
deviceToUseThread2 = 0
deviceToUseThread3 = 0
koRule = POSITIONAL
lagBuffer = 1.0
logAllGTPCommunication = false
logSearchInfo = false
maxTimePondering = 60
multiStoneSuicideLegal = false
nnCacheSizePowerOfTwo = 24
nnMaxBatchSize = 256 …
```

configs: Make match config use GTP temperatures

---

configs/match.cfg

The config settings are set to true by GTP by default, so let's set them to be true in `match.cfg` too.
```
rootSymmetryPruning = true
antiMirror = true
fillDameBeforePass = true
conservativePass = true 
```

configs: Update match config to be closer to GTP defaults

---

compose/transfer/compose.yml
configs/gtp-amcts.cfg
engines/elf/run-gtp.sh
engines/leela/Dockerfile
engines/leela/run-gtp.sh

ELF changes:
* Increase number of playouts from 16,384 to 80,000, since this is the level at which we expect ELF to be superhuman or nearly superhuman based on the ELF paper
Leela changes:
* Turn off Leela resignation (`--resignpct 0`), to be consistent with us turning off KataGo and ELF resignation
* Turn off Leela time limit and instead impose a max visit count of 40000
* Why: Leela defaults to playing with a 1 hour time limit (~30 seconds per move), but depending on time limits will lead to inconsistent results on different hardware
* Turning off the time limit required minor code changes in our fork of Leela: https://github.com/HumanCompatibleAI/leela-zero/pull/1
These parameters were used in the latest transfer experiments (https://www.notion.so/chaiberkeley/transfer-adv-545-0mil-v600 …

Adjust ELF/Leela parameters

---

scripts/score_with_katago.py

Changes: Instead of manually creating a temp directory in `/tmp/` (possibly colliding if we're running the script in parallel on one filesystem), use `tempfile.TemporaryDirectory()` to automatically handle creating/destroying a unique temp directory.
Resolves https://github.com/AlignmentResearch/go_attack/pull/93#discussion_r1092740729
Testing: I ran `score_with_katago.py` on `/nas/ucb/k8/go-attack/baseline-attack/ttseng-katago-raw-20230113-163611/original/model\=kata1-b20c256x2-s5303129600-d1228401921.bin_policy\=edge_visits\=16_pass\=standard_victim\=B/` and checked that the output was equal to `/nas/ucb/k8/go-attack/baseline-attack/ttseng-katago-raw-20230113-163611/rescored/cp127-v16-B-vs-edge.sgfs`

`score_with_katago.py`: Use `tempfile` for cleaner temp directory handling

---

kubernetes/launch-common.sh

Changes:
* Use the flag `--shared-host-dir-slow-tolerant` so that jobs can get scheduled on non-CHAI nodes

kubernetes: Use flag --shared-host-dir-slow-tolerant

---

configs/match.cfg

Changes: Disable `logSearchInfo` for `match`. When enabled, `match` prints the board and some search info after every move in every game, which is very verbose. I've only found this useful for seeing the progress of games when there are few games threads and very high visit counts.

configs/match.cfg: Disable verbose search info

---

kubernetes/train.sh

Bug:
* Say we have a warmstart training run. `train.sh` copies initial tensorflow weights `$INITIAL_WEIGHTS/saved_model/variables/` to a new directory `"$EXPERIMENT_DIR"/train/t0/initial_weights`.
* If `train.sh` restarts (e.g., due to some scheduling or cluster issue), then the copying occurs again, places the tensorflow weights in `$EXPERIMENT_DIR"/train/t0/initial_weights/variables` (this is incorrect)
* If this occurred before any training had occurred, then once there is enough shuffled data to begin a training epoch, the following error will occur. (This does not happen if some training had already occurred before the restart, since `train.sh` will resume using the trained checkpoints, not `initial_weights`)
```
Traceback (most recent call last):
File …
```

train.sh: Fix crash if warmstart restarts early in training

---

kubernetes/train.sh

Changes:
* `MODEL_KIND` for `train.sh` isn't actually used when warmstarting, and the parsing I wrote to populate `MODEL_KIND` when warmstarting sometimes doesn't work. Let's set `MODEL_KIND` to a dummy value instead. (`MODEL_KIND` is a required argument in our version of KataGo, but it's optional in the latest version of KataGo.)

kubernetes/train.sh: Clarify that model kind is unused when warmstarting

---

kubernetes/launch-job.sh

Fix missing space that manifests when the `--warmstart` flag is used with `./launch-job.sh` — we would mistakenly launch a job that runs `victimplay.sh--warmstart` instead of `victimplay.sh --warmstart`.

launch-job: Fix warmstart flag handling

---

scripts/generate_paper_evaluations.py
scripts/paper_evaluations.yml

Updates to `scripts/generate_paper_evaluations.py`:
* Fix: if using the `--run-on-chai` flag, `katago_ckpt_sweep_evaluation` victims should use `/nas/ucb/k8/go-attack/` paths instead of `/shared/` paths
* Fix: I had grossly overestimated the memory footprint of a b40 net because I included the footprint of a b6 adversary plus other fixed memory costs. I've updated a comment in `paper_evaluations.yml` to give more accurate memory footprint measurements.

paper_evaluations: Fix NAS path adjustment, update comment on memory usage per net

---

configs/amcts/components/board-sizes.cfg
configs/compute/1gpu.cfg
configs/compute/2gpu.cfg
configs/compute/3gpu.cfg
configs/compute/4gpu.cfg
configs/compute/5gpu.cfg
configs/compute/6gpu.cfg
configs/compute/7gpu.cfg
configs/compute/8gpu.cfg
kubernetes/launch-baseline-attack.sh
kubernetes/launch-common.sh
kubernetes/launch-gtp-eval.sh
kubernetes/launch-job.sh
kubernetes/launch-match.sh

Update some config/param values that I've used in most of my jobs recently:
* Increase the proportion of 19x19 games to the same proportion KataGo uses in its later runs (53.6%) (we care most about 19x19 games so this seems reasonable to me)
* Reduce `numGameThreads`—this matters for victimplay, since if `numGameThreads` is high and the number of victimplay workers is high, then there will be a lot of stale games still in flight when we move on to a later model checkpoint
* Always use Weka volume: we've copied `/nas/` data to the Weka volume so let's just default to using the Weka volume
* Shorten job names boilerplate: Hofvarpnir now appends the user's Slack member ID to pod names so now we only have 38 characters for custom job names rather than 50. Let's shorten …

kubernetes+config: Update config values

---

configs/gtp-amcts.cfg
configs/kgs-bot/adversary_bot.cfg

We upgraded from KataGo v1.10 to v1.11 with Nora's Nov 2022 merge PR, and there were some params that changed between v1.10 and v1.11. I noted in some config files with params need to be changed to get close to v1.10 behavior. 
This PR modifies the params in GTP files so that they affect both the bot and the bot being simulated in AMCTS (e.g., params were changed from `fpuParentWeightByVisitedPolicy0` to `fpuParentWeightByVisitedPolicy`). Based on some GTP evaluations I had been running, I believe this actually does make a difference in win rate / behavior with our cyclic/pass adversaries, though unfortunately I deleted the data from those evaluations since I didn't think that the data was notable at the time.

configs: Set v1.10 params properly

---

configs/compute/1gpu.cfg
configs/compute/2gpu.cfg
configs/compute/3gpu.cfg
configs/compute/4gpu.cfg
configs/compute/5gpu.cfg
configs/compute/6gpu.cfg
configs/compute/7gpu.cfg
configs/compute/8gpu.cfg
configs/match-1gpu.cfg

Changes:
* Increase default numGameThreads per GPU from 32 to 128. 
* We had decreased numGameThreads from 256 to 32 out of concern that during victimplay, having high game threads would mean we would have a lot of lagging games from previous models. But setting numGameThreads = 16 gave much less game throughput, even though GPU utilization looked high from `nvidia-smi`.
* Based on a crude benchmark, numGameThreads should be 128+ for high game throughput: https://www.notion.so/chaiberkeley/debugging-victimplay-throughput-being-lower-than-expected-bc376db69a5a4343bd6c609dcec1ca4b?pvs=4#82543a2589c348d3ae3940584fd72abf
* Decrease cache size `nnCacheSizePowerOfTwo` from 24 to 21. Each cache size entry is 1.5KB so this decreases cache size per net from 25GB to 3GB. 
* Flamingo nodes' memory …

configs: Increase game threads, decrease cache size

---

configs/sabaki/gtp-adv600-vm1-s.cfg

After updating to KataGo v1.11, we needed to reset some config params to match old v1.10 params that the cyclic adversary was trained on: https://github.com/AlignmentResearch/go_attack/blob/b4305ccf2e296d74b142c34c18b782f2f54baf48/configs/kgs-bot/adversary_bot.cfg#L130-L134
This PR copies those config params to the Sabaki config as well.

Adjust Sabaki config params to account for KataGo v1.11 

---

sabaki/README.md

Update Sabaki README so that which command to run in order to execute the cyclic adversary is clearer.

Sabaki: More clearly indicate the command to run cyclic adv

---

configs/active-experiment.cfg

Edits to active-experiment.cfg:
* Edit comment on `maxVisits0` to remark that it's usually overridden by the curriculum
* Remove compute params since those are covered by `compute/1gpu.cfg`
* Add note on `useLcbForSelfplayMove`

active-experiment: Remove compute params, add comment on LCB

---

kubernetes/iterated-training/shuffle-and-export.sh
kubernetes/launch-job.sh
kubernetes/shuffle-and-export.sh

Changes to `kubernetes/shuffle-and-export.sh`:
* Add command-line flag for preseeding data with data from a previous run. We found that this was needed to make warm-starting runs train well.
* Move the gatekeeper parameter to be a command-line flag as well
* Pass extra arguments of `kubernetes/shuffle-and-export.sh` onto `KataGo-custom/python/selfplay/shuffle_and_export_loop.sh` — this is useful for passing flags to adjust the shuffler window size

shuffle-and-export: Add flag for pre-seeding data

---

scripts/prune_shuffleddata.py

Our volume on flamingo was getting full, so I wrote this script to delete old `shuffledata` directories. It freed up 1.5T of disk usage.

scripts: Add script for deleting old `shuffleddata` directories

---

compose/cpp/Dockerfile

Previously we pinned libc6 to version 2.31. This no longer works, with the following error on `apt install`:
```
E: Version '2.31-0ubuntu9.9' for 'libc6' was not found
E: Version '2.31-0ubuntu9.9' for 'libc6-dev' was not found
E: Version '2.31-0ubuntu9.9' for 'libc-dev-bin' was not found
```
I removed the pin, rebuilt the image, and checked the `libc` version installed via `ldd --version`. The version is `2.31-0ubuntu9.12`, so I think we're safe to stop forcing the version.

C++ Dockerfile: Remove pin of libc version number

---

.gitmodules
compose/python/Dockerfile
compose/python/requirements.txt
configs/amcts/base.cfg
configs/amcts/victimplay.cfg
configs/gtp-amcts.cfg
configs/gtp-base.cfg
configs/gtp-raw.cfg
configs/kgs-bot/adversary_bot.cfg
configs/match.cfg
configs/sabaki/gtp-adv600-vm1-s.cfg
kubernetes/shuffle-and-export.sh
kubernetes/train.sh
scripts/generate_paper_evaluations.py
scripts/paper_evaluations.yml

Update `KataGo-custom` to v1.12.4.
Model training still uses TF so that we can finetune our TF cyclic adversary. If we want to finetune the new architectures  using PyTorch model training, we'll need to further edit kubernetes/train.sh since some of the flags to train.py have changed (e.g., model kind is a flag -model-kind instead of a positional argument, and warmstarting is done with the -initial-checkpoint flag instead of done by copying files into a initial_weights directory). `kubernetes/shuffle_and_export.sh` would need to switch to using the PyTorch code as well, since the `shuffleddata` format is different between TF and PyTorch.

Upgrade to KataGo v1.12.4

---

sabaki/README.md
sabaki/scripts/download-models.sh

I updated our [Google drive of models](https://drive.google.com/drive/u/3/folders/1-bGX-NQOh6MuRPoXJgYHb9-jWRJvviSg):
* Delete older cyclic models (s349m, s498m)
* Upload models used in our defense paper: ViT, ViT adversary, v9, a9, atari adversary, continuous adversary, gift adversary, cyclic-s227m, attack-may23
* Upload Python training weights for every model
* Upload training data for all of our paper models, except for pass adversary (pass adversary data got deleted when /nas/ucb/tony was deleted)
This PR updates the download script in `sabaki/` to not use the older cyclic models and to point to the new download URLs for the cyclic + pass adversary.

sabaki: Update models

---

configs/compute/1gpu.cfg
configs/compute/2gpu.cfg
configs/compute/3gpu.cfg
configs/compute/4gpu.cfg
configs/compute/5gpu.cfg
configs/compute/6gpu.cfg
configs/compute/7gpu.cfg
configs/compute/8gpu.cfg

* Increase game threads 128->256: I had found [several months back](https://www.notion.so/chaiberkeley/debugging-victimplay-throughput-being-lower-than-expected-bc376db69a5a4343bd6c609dcec1ca4b?pvs=4#82543a2589c348d3ae3940584fd72abf) that 256 game threads had a little more throughput than 128 threads
* Increase server threads to match the number of GPUs, otherwise we're not actually making use of multiple GPUs
* We previously were doing this but I had accidentally removed it in a [previous PR](https://github.com/AlignmentResearch/go_attack/pull/121)

configs/compute: Increase game threads 128→256, fix multi-GPU usage

---

kubernetes/evaluate-loop.sh

* Handle finding Torchscript `.pt` trained models instead of `.bin.gz` (strictly speaking this never happens since our adversaries are always `.bin.gz`. The ViT is a `.pt` but it's a self-play run which evaluate_loop does not handle. But this makes it easier to modify evaluate_loop to work for the ViT run)
* Always disable pass hardening for eval, we usually just want hardening in training to avoid degenerating into the pass attack
* Misc `shellcheck` fixes

evaluate_loop: Misc improvements

---

configs/active-experiment.cfg
configs/amcts/victimplay.cfg

Update active-experiment.cfg to match the config params used in many of our recent training runs:
* Make victim params closer to eval
* Make adversary params closer to most up-to-date KataGo-raw training config https://github.com/lightvector/KataGo/blob/master/cpp/configs/training/selfplay8mainb18.cfg
E.g., (1) `atari-adversary` and (2) `a9` were trained with these params, which suggests that with these params we can still (1) discover a cyclic attack (at least if warmstarted from cyclic-s227m) and (2) train a potent cyclic attack

configs: Make active-experiment.cfg match latest experiments

---

.gitmodules

Kaniko, which we use to build images on Flamingo, does not work with SSH submodules, because it will hit an auth error from not having the appropriate SSH key. We could create a Kubernetes secret containing an SSH private key and mount it into the Kaniko build container, but I think this is a security vulnerability since GitHub SSH has no fine-grained permission control, it just gives full read/write access to all your repos (e.g., say someone infiltrates the official Kaniko repo and adds malicious code that steals your SSH private key).
This PR changes go_attack submodules to use HTTPS instead of SSH. This allows Kaniko to build the go_attack Docker image. I've also added a few sentences in the [Flamingo wiki](https://github.com/AlignmentResearch/flamingo/wiki/Build-Docker-images-on-the-c …

gitmodules: Switch from SSH to HTTPS to make Kaniko build work more easily

---

configs/active-experiment.cfg
configs/match.cfg

A few config changes I failed to include in #144:
* In training, victim should have score utility 0.1 rather than 0.05 (documented in paper in appendix but failed to add in #144)
* In eval, conservativePass should be on to match GTP default
* Add comment about why rootSymmetryPruning is not the same between training and eval

active-experiment: More victim config fixes
